parser: babel-eslint

env:
  browser: true
  node: true

extends:
  - airbnb
  - eslint:recommended

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins:
  - react

rules:
  linebreak-style: off
  array-bracket-spacing: [error]
  global-require: off
  semi: [error, never]
  comma-dangle: [error, never]
  comma-style: [error, last]
  computed-property-spacing: [error, never]
  func-call-spacing: [error, never]
  id-length: [error, {"exceptions": ["_"]}]
  class-methods-use-this: off
  key-spacing: [error]
  consistent-return: off
  no-underscore-dangle: [error, {allowAfterThis: true}]
  no-multi-assign: off
  no-param-reassign: off
  no-magic-numbers: [error]
  no-constant-condition: [error]
  no-inline-comments: [error]
  no-lonely-if: [error]
  no-mixed-operators: [error]
  no-extra-parens: [error, all, {ignoreJSX: multi-line}]
  no-unneeded-ternary: [error]
  no-else-return: [error]
  no-confusing-arrow: off
  no-unused-expressions: [error, {allowShortCircuit: true}]
  yoda: [error]
  complexity: [error, 3]
  max-depth: [error, 1]
  max-lines: [error, 300]
  max-nested-callbacks: [error, 3]
  max-params: [error, 4]
  newline-per-chained-call: [error]
  react/prefer-stateless-function: off
  react/jsx-filename-extension: [1, {"extensions": [".spec.js", ".jsx"]}]
  react/forbid-prop-types: off
  react/require-default-props: off
  react/no-find-dom-node: off
  react/no-array-index-key: off
  import/no-extraneous-dependencies: [error, {devDependencies: true}]
  import/prefer-default-export: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/interactive-supports-focus: off

settings:
  import/resolver:
    webpack:
      config: "./webpack.config.js"
